export const AuditAction = {
  USER_CREATED: "user_created",
  USER_UPDATED: "user_updated",
  USER_SUSPENDED: "user_suspended",
  USER_ACTIVATED: "user_activated",
  ROLE_ASSIGNED: "role_assigned",
  ROLE_CHANGED: "role_changed",
  ROLE_CREATED: "role_created",
  ROLE_UPDATED: "role_updated",
  PRIVILEGE_GRANTED: "privilege_granted",
  PRIVILEGE_REVOKED: "privilege_revoked",
  INVITE_SENT: "invite_sent",
  INVITE_ACCEPTED: "invite_accepted",
  INVITE_REVOKED: "invite_revoked",
  INVITE_EXPIRED: "invite_expired",
  SESSION_CREATED: "session_created",
  SESSION_REVOKED: "session_revoked",
  SESSION_REVOKED_BY_ADMIN: "session_revoked_by_admin",
  LOGIN_SUCCESS: "login_success",
  LOGIN_FAILED: "login_failed",
  LOGOUT: "logout",
  OTP_SENT: "otp_sent",
  OTP_VERIFIED: "otp_verified",
  SSO_LINKED: "sso_linked",
  ACCOUNT_CREATED: "account_created",
  ACCOUNT_UPDATED: "account_updated",
  PASSWORD_CHANGED: "password_changed",
} as const;

export type AuditActionType = (typeof AuditAction)[keyof typeof AuditAction];
